// <auto-generated />
using System;
using Compass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Compass.Migrations
{
    [DbContext(typeof(CompassDbContext))]
    [Migration("20251020114127_AddThemeToObjective")]
    partial class AddThemeToObjective
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Compass.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActionSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FipsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActionSourceId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("FipsId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("ParentActionId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Compass.Models.ActionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("SortOrder");

                    b.ToTable("ActionSources");
                });

            modelBuilder.Entity("Compass.Models.ApiRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryString")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenId");

                    b.HasIndex("IsSuccess");

                    b.HasIndex("RequestTimestamp");

                    b.ToTable("ApiRequestLogs");
                });

            modelBuilder.Entity("Compass.Models.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("Compass.Models.ApiTokenPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiTokenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenId", "Resource")
                        .IsUnique();

                    b.ToTable("ApiTokenPermissions");
                });

            modelBuilder.Entity("Compass.Models.AssessmentCriteriaResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Attainment")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionalStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PracticeAreaId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalStandardId", "ThemeId", "PracticeAreaId", "CriteriaCode");

                    b.HasIndex("AssessmentId", "FunctionalStandardId", "ThemeId", "PracticeAreaId", "CriteriaCode")
                        .IsUnique();

                    b.ToTable("AssessmentCriteriaResponses");
                });

            modelBuilder.Entity("Compass.Models.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionalStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PracticeAreaId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("Compass.Models.EnterpriseMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HintText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidFromMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidFromYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("EnterpriseMetrics");
                });

            modelBuilder.Entity("Compass.Models.EnterpriseMetricValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnterpriseMetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnterpriseReturnId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseMetricId");

                    b.HasIndex("EnterpriseReturnId", "EnterpriseMetricId")
                        .IsUnique();

                    b.ToTable("EnterpriseMetricValues");
                });

            modelBuilder.Entity("Compass.Models.EnterpriseReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("EnterpriseReturns");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FunctionalStandards");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandardAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionalStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalStandardId");

                    b.ToTable("FunctionalStandardAssessments");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandardTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionalStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalStandardId", "ThemeId")
                        .IsUnique();

                    b.ToTable("FunctionalStandardThemes");
                });

            modelBuilder.Entity("Compass.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlockedFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FipsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Workaround")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FipsId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetResolutionDate");

                    b.HasIndex("Severity", "Priority");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Compass.Models.IssueAction", b =>
                {
                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IssueId", "ActionId");

                    b.HasIndex("ActionId");

                    b.ToTable("IssueActions");
                });

            modelBuilder.Entity("Compass.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BaselineDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FipsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("FipsId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Status");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Compass.Models.MilestoneAction", b =>
                {
                    b.Property<int>("MilestoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MilestoneId", "ActionId");

                    b.HasIndex("ActionId");

                    b.ToTable("MilestoneActions");
                });

            modelBuilder.Entity("Compass.Models.MilestoneIssue", b =>
                {
                    b.Property<int>("MilestoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MilestoneId", "IssueId");

                    b.HasIndex("IssueId");

                    b.ToTable("MilestoneIssues");
                });

            modelBuilder.Entity("Compass.Models.MilestoneRisk", b =>
                {
                    b.Property<int>("MilestoneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MilestoneId", "RiskId");

                    b.HasIndex("RiskId");

                    b.ToTable("MilestoneRisks");
                });

            modelBuilder.Entity("Compass.Models.Objective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RagStatus")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessMeasures")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RagStatus");

                    b.HasIndex("Status");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("Compass.Models.PerformanceMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicablePhases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HintText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidFromMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidFromYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("Compass.Models.PracticeArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionalStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PracticeAreaId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PracticeAreas");
                });

            modelBuilder.Entity("Compass.Models.ProductMetricValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceMetricId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductReturnId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceMetricId");

                    b.HasIndex("ProductReturnId", "PerformanceMetricId")
                        .IsUnique();

                    b.ToTable("ProductMetricValues");
                });

            modelBuilder.Entity("Compass.Models.ProductReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FipsId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FipsId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ProductReturns");
                });

            modelBuilder.Entity("Compass.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessArea")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FipsId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImpactRating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikelihoodRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjectiveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximityDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResidualImpact")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResidualLikelihood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Response")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RiskTierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FipsId");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("ProximityDate");

                    b.HasIndex("RiskScore")
                        .IsDescending();

                    b.HasIndex("RiskTierId");

                    b.HasIndex("Status");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("Compass.Models.RiskAction", b =>
                {
                    b.Property<int>("RiskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RiskId", "ActionId");

                    b.HasIndex("ActionId");

                    b.ToTable("RiskActions");
                });

            modelBuilder.Entity("Compass.Models.RiskRiskType", b =>
                {
                    b.Property<int>("RiskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RiskId", "RiskTypeId");

                    b.HasIndex("RiskTypeId");

                    b.ToTable("RiskRiskTypes");
                });

            modelBuilder.Entity("Compass.Models.RiskTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("SortOrder");

                    b.ToTable("RiskTiers");
                });

            modelBuilder.Entity("Compass.Models.RiskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("RiskTypes");
                });

            modelBuilder.Entity("Compass.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Compass.Models.UserPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredBusinessAreas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Compass.Models.Action", b =>
                {
                    b.HasOne("Compass.Models.ActionSource", "ActionSource")
                        .WithMany()
                        .HasForeignKey("ActionSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Compass.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.HasOne("Compass.Models.Objective", "Objective")
                        .WithMany("Actions")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Compass.Models.Action", "ParentAction")
                        .WithMany("SubActions")
                        .HasForeignKey("ParentActionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionSource");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Objective");

                    b.Navigation("ParentAction");
                });

            modelBuilder.Entity("Compass.Models.ApiRequestLog", b =>
                {
                    b.HasOne("Compass.Models.ApiToken", "ApiToken")
                        .WithMany("RequestLogs")
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiToken");
                });

            modelBuilder.Entity("Compass.Models.ApiTokenPermission", b =>
                {
                    b.HasOne("Compass.Models.ApiToken", "ApiToken")
                        .WithMany("Permissions")
                        .HasForeignKey("ApiTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiToken");
                });

            modelBuilder.Entity("Compass.Models.AssessmentCriteriaResponse", b =>
                {
                    b.HasOne("Compass.Models.FunctionalStandardAssessment", "Assessment")
                        .WithMany("CriteriaResponses")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("FunctionalStandardId", "ThemeId", "PracticeAreaId", "CriteriaCode")
                        .HasPrincipalKey("FunctionalStandardId", "ThemeId", "PracticeAreaId", "CriteriaCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Compass.Models.Criterion", b =>
                {
                    b.HasOne("Compass.Models.PracticeArea", "PracticeArea")
                        .WithMany("Criteria")
                        .HasForeignKey("FunctionalStandardId", "ThemeId", "PracticeAreaId")
                        .HasPrincipalKey("FunctionalStandardId", "ThemeId", "PracticeAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticeArea");
                });

            modelBuilder.Entity("Compass.Models.EnterpriseMetricValue", b =>
                {
                    b.HasOne("Compass.Models.EnterpriseMetric", "EnterpriseMetric")
                        .WithMany()
                        .HasForeignKey("EnterpriseMetricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Compass.Models.EnterpriseReturn", "EnterpriseReturn")
                        .WithMany("MetricValues")
                        .HasForeignKey("EnterpriseReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnterpriseMetric");

                    b.Navigation("EnterpriseReturn");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandardAssessment", b =>
                {
                    b.HasOne("Compass.Models.FunctionalStandard", "FunctionalStandard")
                        .WithMany()
                        .HasForeignKey("FunctionalStandardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FunctionalStandard");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandardTheme", b =>
                {
                    b.HasOne("Compass.Models.FunctionalStandard", "FunctionalStandard")
                        .WithMany("Themes")
                        .HasForeignKey("FunctionalStandardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalStandard");
                });

            modelBuilder.Entity("Compass.Models.Issue", b =>
                {
                    b.HasOne("Compass.Models.Objective", "Objective")
                        .WithMany("Issues")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Compass.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("Objective");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Compass.Models.IssueAction", b =>
                {
                    b.HasOne("Compass.Models.Action", "Action")
                        .WithMany("IssueActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.Issue", "Issue")
                        .WithMany("IssueActions")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Compass.Models.Milestone", b =>
                {
                    b.HasOne("Compass.Models.Objective", "Objective")
                        .WithMany("Milestones")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Compass.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("Objective");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Compass.Models.MilestoneAction", b =>
                {
                    b.HasOne("Compass.Models.Action", "Action")
                        .WithMany("MilestoneActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.Milestone", "Milestone")
                        .WithMany("MilestoneActions")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("Compass.Models.MilestoneIssue", b =>
                {
                    b.HasOne("Compass.Models.Issue", "Issue")
                        .WithMany("MilestoneIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.Milestone", "Milestone")
                        .WithMany("MilestoneIssues")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("Compass.Models.MilestoneRisk", b =>
                {
                    b.HasOne("Compass.Models.Milestone", "Milestone")
                        .WithMany("MilestoneRisks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.Risk", "Risk")
                        .WithMany("MilestoneRisks")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Compass.Models.Objective", b =>
                {
                    b.HasOne("Compass.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Compass.Models.PracticeArea", b =>
                {
                    b.HasOne("Compass.Models.FunctionalStandardTheme", "Theme")
                        .WithMany("PracticeAreas")
                        .HasForeignKey("FunctionalStandardId", "ThemeId")
                        .HasPrincipalKey("FunctionalStandardId", "ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Compass.Models.ProductMetricValue", b =>
                {
                    b.HasOne("Compass.Models.PerformanceMetric", "PerformanceMetric")
                        .WithMany()
                        .HasForeignKey("PerformanceMetricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Compass.Models.ProductReturn", "ProductReturn")
                        .WithMany("MetricValues")
                        .HasForeignKey("ProductReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformanceMetric");

                    b.Navigation("ProductReturn");
                });

            modelBuilder.Entity("Compass.Models.Risk", b =>
                {
                    b.HasOne("Compass.Models.Objective", "Objective")
                        .WithMany("Risks")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Compass.Models.RiskTier", "RiskTier")
                        .WithMany()
                        .HasForeignKey("RiskTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Objective");

                    b.Navigation("RiskTier");
                });

            modelBuilder.Entity("Compass.Models.RiskAction", b =>
                {
                    b.HasOne("Compass.Models.Action", "Action")
                        .WithMany("RiskActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.Risk", "Risk")
                        .WithMany("RiskActions")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Compass.Models.RiskRiskType", b =>
                {
                    b.HasOne("Compass.Models.Risk", "Risk")
                        .WithMany("RiskRiskTypes")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Compass.Models.RiskType", "RiskType")
                        .WithMany()
                        .HasForeignKey("RiskTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("RiskType");
                });

            modelBuilder.Entity("Compass.Models.UserPreference", b =>
                {
                    b.HasOne("Compass.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Compass.Models.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Compass.Models.Action", b =>
                {
                    b.Navigation("IssueActions");

                    b.Navigation("MilestoneActions");

                    b.Navigation("RiskActions");

                    b.Navigation("SubActions");
                });

            modelBuilder.Entity("Compass.Models.ApiToken", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("RequestLogs");
                });

            modelBuilder.Entity("Compass.Models.EnterpriseReturn", b =>
                {
                    b.Navigation("MetricValues");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandard", b =>
                {
                    b.Navigation("Themes");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandardAssessment", b =>
                {
                    b.Navigation("CriteriaResponses");
                });

            modelBuilder.Entity("Compass.Models.FunctionalStandardTheme", b =>
                {
                    b.Navigation("PracticeAreas");
                });

            modelBuilder.Entity("Compass.Models.Issue", b =>
                {
                    b.Navigation("IssueActions");

                    b.Navigation("MilestoneIssues");
                });

            modelBuilder.Entity("Compass.Models.Milestone", b =>
                {
                    b.Navigation("MilestoneActions");

                    b.Navigation("MilestoneIssues");

                    b.Navigation("MilestoneRisks");
                });

            modelBuilder.Entity("Compass.Models.Objective", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Issues");

                    b.Navigation("Milestones");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Compass.Models.PracticeArea", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Compass.Models.ProductReturn", b =>
                {
                    b.Navigation("MetricValues");
                });

            modelBuilder.Entity("Compass.Models.Risk", b =>
                {
                    b.Navigation("MilestoneRisks");

                    b.Navigation("RiskActions");

                    b.Navigation("RiskRiskTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
